name = "trading-assistant-ai"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = [
  "0 * * * 1-5"
]

[[d1_databases]]
binding = "DB"
database_name = "trading-assistant-ai"
database_id = "96417c47-1152-465b-9ff2-cec6fe394990"

[[kv_namespaces]]
binding = "KV"
id = "a82afed2ad864e6bb1d11cd57e2f8219"

[assets]
directory = "./dist/ui"

[vars]
ENVIRONMENT = "production"
MARKET_DATA_PROVIDER = "live"
